runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_ENV: local   # or production
  APP_DEBUG : true # or false
  APP_LOG: errorlog
  APP_KEY: base64:iOrhpFsA3Ftnu69ze0QhEM9tHS72FxzOG5Sih8puPme=
  STORAGE_DIR: /tmp